import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";
import BackToTopBottom from "@/components/ui/BackToTopBottom";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Navbar/>
        <main className="mt-8">
          {children}
        </main>
        <Footer/>
        <BackToTopBottom/>
      </body>
    </html>
    </ClerkProvider>
  );
}
