import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";
import BackToTopBottom from "@/components/ui/BackToTopBottom";
import Script from "next/script";


export const metadata: Metadata = {
  title: "Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`antialiased`}
        >
         

          {/* ✅ Social Bar */}


          {/* <script type='text/javascript' src='//madeupvigourpoll.com/82/ed/6b/82ed6bcad8801f9523d775023bf07cce.js'></script> */}
          <Navbar />

          {/* ✅ Adsterra Native Banner */}
          <div id="container-713370ad3840a8be04034b9fe2003723"></div>
          <Script
            id="adsterra-nativebanner"
            strategy="afterInteractive"
            src="//madeupvigourpoll.com/713370ad3840a8be04034b9fe2003723/invoke.js"
          />

          <main className="mt-8">
            {children}
          </main>
          <Footer />
          <BackToTopBottom />
          {/* Vercel Analytics */}
          <Analytics />

          {/* Optional: Speed Insights for testing (doesn't render UI) */}
          <SpeedInsights />
          <Script
            id="adsterra-socialbar"
            strategy="afterInteractive"
            src="//madeupvigourpoll.com/82/ed/6b/82ed6bcad8801f9523d775023bf07cce.js"
          />

        </body>
      </html>
    </ClerkProvider>
  );
}
