import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";
import BackToTopBottom from "@/components/ui/BackToTopBottom";
import Script from "next/script";



export const metadata: Metadata = {
  title: "Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`antialiased`}
        >
          {/* ✅ HilltopAds Popunder Script */}
          <Script
            id="hilltopads-popunder"
            strategy="afterInteractive" // পেজ লোড হওয়ার পর চালু হবে
            dangerouslySetInnerHTML={{
              __html: `
      (function(){
        var script = document.createElement("script");
        script.type = "text/javascript";
        script.src = "//data527.click/64bcda9c31f60cb25df8/c3ab775ffb/?placementName=default";
        script.async = true;
        document.body.appendChild(script);
      })();
    `,
            }}
          />
          {/* <script type="text/javascript" src="//data527.click/64bcda9c31f60cb25df8/c3ab775ffb/?placementName=default"></script> */}
          <Navbar />

          <main className="mt-8">
            {children}
          </main>
          <Footer />
          <BackToTopBottom />
        </body>
      </html>
    </ClerkProvider>
  );
}
